spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: Asia/Seoul
  timezone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 300000
      maximum-pool-size: 10
      connection-timeout: 60000
      initialization-fail-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
  application:
    name: movewave_java
  data:
    redis.host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email

logging:
  level:
    root: INFO

resilience4j:
  retry:
    instances:
      flaskEmotion:
        maxAttempts: 3           # 최대 3번 시도
        waitDuration: 1s         # 1초 간격
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
    timelimiter:
      instances:
        flaskEmotion:
          timeoutDuration: 6s      # 6초 넘으면 fallback
  circuitbreaker:
    instances:
      flaskEmotion:
        registerHealthIndicator: true
        slidingWindowSize: 5            # 최근 5번 기준
        minimumNumberOfCalls: 5
        failureRateThreshold: 50        # 50% 실패 시 circuit open
        waitDurationInOpenState: 10s    # 10초 후 반쯤 열림(half-open)
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s   # 5초 넘으면 느린 호출로 간주

api:
  key: ${API_KEY}

jwt:
  expiration-time: '3600000'
  refresh-expiration-time: '86400000'
  secret: ${JWT_SECRET}

redirect:
  url: ${REDIRECT_URL}

