# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movewave-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: movewave.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movewave-app-service
                port:
                  number: 8080
