apiVersion: apps/v1 # 리소스 버전
kind: Deployment  # 리소스 종류
metadata: # deployment의 이름을 정의
  name: movewave-app
spec: # 배포 스펙 정의
  replicas: 1 # 1개의 pod만 실행
  selector: # 어떤 pod이 이 Deployment의 관리 대상인지 지정
    matchLabels:
      app: movewave-app # Deployment가 관리할 pod이 무엇인지 찾는 조건
  template: # pod 템플릿 정의
    metadata:
      labels:
        app: movewave-app
    spec:
      containers: # 여러 개의 컨테이너 중 하나 정의
        - name: movewave-app # 컨테이너 이름
          image: movewave-app:latest # 사용할 도커 이미지
          imagePullPolicy: IfNotPresent # 로컬에 이미지가 있으면 재다운로드 안함
          ports: # pod 내부에서 오픈할 포트
            - containerPort: 8080
          env: # 환경변수 설정
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: DB_URL
              value: "jdbc:mysql://mysql:3306/movewave?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: DB_USERNAME
              value: "manager"
            - name: DB_PASSWORD
              value: "manager0"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: GOOGLE_CLIENT_ID
              value: "30000074251-2u52qvtdirm7iv6tv0i4jf0ea1susjof.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "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"
            - name: API_KEY
              value: "AIzaSyAqTEiVijGjOqxp_cchARlY8hI-CkERORw"
            - name: JWT_SECRET
              value: "U9f4wG5wrk1cOhtBh0T2l4BRY8B0/j6H7vRvXmvqMhOcUQstYjAb648Nkr2dDMFn"
            - name: REDIRECT_URL
              value: "http://localhost:3000"
            - name: FASTAPI_URL
              value: "http://movewave_python:5000"
