apiVersion: apps/v1 # 리소스 버전
kind: Deployment  # 리소스 종류
metadata: # deployment의 이름을 정의
  name: movewave-app
spec: # 배포 스펙 정의
  replicas: 1 # 1개의 pod만 실행
  selector: # 어떤 pod이 이 Deployment의 관리 대상인지 지정
    matchLabels:
      app: movewave-app # Deployment가 관리할 pod이 무엇인지 찾는 조건
  template: # pod 템플릿 정의
    metadata:
      labels:
        app: movewave-app
    spec:
      containers: # 여러 개의 컨테이너 중 하나 정의
        - name: movewave-app # 컨테이너 이름
          image: movewave-app:latest # 사용할 도커 이미지
          imagePullPolicy: IfNotPresent # 로컬에 이미지가 있으면 재다운로드 안함
          ports: # pod 내부에서 오픈할 포트
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: REDIS_PORT
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: JWT_SECRET
            - name: REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: REDIRECT_URL
            - name: FASTAPI_URL
              valueFrom:
                secretKeyRef:
                  name: movewave-secrets
                  key: FASTAPI_URL
